services:
  mongodb:
    image: mongo:latest
    container_name: edmond
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: jeyamedicalMaster
      MONGO_INITDB_ROOT_PASSWORD: superStrongJeyamedicalMasterpasSWord--231
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
